version: "3.8"
services:
  trustr-vol:
    image: inndata/trustr-volunteer:latest
    container_name: trustr-vol
    volumes:
      - /trustr-jenkins/environment:/app/environment
    ports:
      - "6046:8080"
    networks:
      - internal
      - proxy

networks:
  proxy:
    external: true
  internal:
    external: true
